name: Publish on master

on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grant execute permission for `./gradlew`
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 11
          cache: gradle

      - name: Publish artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :lang:publish :compiler-backend:publish :compiler-frontend:publish :adapter-common:publish --no-daemon --warning-mode=all --stacktrace